name: Build Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  merge_group:

jobs:
  pr-merge:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      # Checkout latest commit
      - uses: actions/checkout@v3

      # Set up latest Java for build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Post test results
      - name: Publish Test Report
        id: test-report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/*.xml'
          detailed_summary: true